### ISSUE TITLE
antivirus amp installation in alfresco all in one project to deploy using docker

### ISSUE THREAD

**Issue by melani016** [fegorama/alfviral#19]
i have downloaded alfresco  all in one project(4.1.0) and installed antivirus amp files(platform& share) using mmt tool in docker container.
getting below error
anti-acs_1       |  2021-02-16 11:36:17,865  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
anti-acs_1       |  org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.alfresco.web.config.WebClientConfigBootstrap] for bean with name 'alfviral.webclient.configBootstrap' defined in class path resource [**alfresco/module/alfviral/context/service-context.xml]; nested exception is java.lang.ClassNotFoundException: org.alfresco.web.config.WebClientConfigBootstrap**

can you please tell how do i specify alfviral.command.exec path in antiviral.properties?

**Comment by fegorama** [comment]
Hi!

Is de complete path and executable binary of antivirus or batch with file
to scan as parameter.

For example:
  In Windows:
    alfviral.command.exec=clamscan.exe
  In Linux:
    alfviral.command.exec=clanscan

My recomedation is use INSTREAM or ICAP protocol.

I need export project to new SDK and update to Alfresco 6.2 and containters
(Docker and Kubernetes).

Thank you for use this module and best regards,

Fernando González Ruano
Skype: fegorama

LinkedIn: https://www.linkedin.com/in/fegor/
GitHub: https://github.com/fegorama/
Blog: http://www.fegor.com/

**Comment by viper0131** [comment]
Hello Fernando,

We are also looking into virusscanning our Alfresco documents (on read).
I found your AMP files, but it seems outdated for our alfresco 6.2 installation (inside docker)

Do you have plans (and time ;-) ) to make it compatible again?

**Comment by fegorama** [comment]
Hi!

Yes, in this week or next I upload the new version with Alfresco SDK 4.1
for docker.

Best regards,


Fernando González Ruano
Skype: fegorama

LinkedIn: https://www.linkedin.com/in/fegor/
GitHub: https://github.com/fegorama/
Blog: http://www.fegor.com/

**Comment by fegorama** [comment]
I have push of the new version with the Alfresco SDK 4.1

Best regards.

**Comment by viper0131** [comment]
Thank you, will check it out right away

**Comment by melani016** [comment]
Thank you for updating the code.
i am still facing the issue "The Document could not be scanned" when i click on "scan file".
Attached the docker-compose.yml in text format 
 Below is alfviral.properties file.
alfviral.command.exec=\"docker exec -ti alfviral-clamav-icap clamscan\"
# Config for ICAP protocol
alfviral.icap.host=127.0.0.1
alfviral.icap.port=1344
alfviral.icap.service=srv_clamav
# Modes: COMMAND, INSTREAM, VIRUSTOTAL, ICAP
alfviral.mode=ICAP

Please check and let me know what is wrong


[docker-compose.txt](https://github.com/fegorama/alfviral/files/6189134/docker-compose.txt)

**Comment by fegorama** [comment]
Hi!

This example is only for testing because calling to containers is very slow.

Please, How is your configuration?
1) Alfresco platform is in docker?
2) Clamscan is in other docker?
3) Do you use alfviral-antivirus docker and alfviral-platform docker?

Best regards,

Fernando González Ruano
Skype: fegorama

LinkedIn: https://www.linkedin.com/in/fegor/
GitHub: https://github.com/fegorama/
Blog: http://www.fegor.com/

**Comment by melani016** [comment]
Thank you for the support.. it is working now.

however webscript is able to scan only documents from sites/
not able to scan from sharedfiles Folder. seems like i need to do some changes in webscript.

**Comment by fegorama** [comment]
Hi!

I ended some changes this week and I will push project this weekend.

Best regards,

Fernando González Ruano
Skype: fegorama

LinkedIn: https://www.linkedin.com/in/fegor/
GitHub: https://github.com/fegorama/
Blog: http://www.fegor.com/

**Comment by melani016** [comment]
Thank you @fegorama
