### ISSUE TITLE
Alfviral Usage and Version Compatibility

### ISSUE THREAD

**Issue by AlexWang-16** [fegorama/alfviral#23]
Hi @fegorama,

Thank you for creating this awesome Alfresco module. I have a few questions that I could not find in the documentation provided in this repo that I hope I could get answers to.

1. Does alfviral currently support Alfresco Repository and Alfresco share v7.2? 
2. I currently run alfresco in Kubernetes. I have converted alfviral's docker-compose.yml into kubernetes yaml files and managed to deploy alfviral share and alfviral-antivirus. How can I verify that it is working? Would you have any usage documentations that I can look into for how to use alfviral?
3. How can I customize alfviral's behaviour? For example, the email address for infected file notifications and quarantine or delete infected file immediately.
4. What is the functionality of alfviral-platform?
5. alfviral-platform project's docker-compose.yml contains reference to Alfresco Search Services image v1.2.0. I'm currently using Alfresco Search Services 1.4.3. Is it ok if I changed the image to reference v1.4.3?

Thank you for your time.

**Comment by fegorama** [comment]
Hi @AlexWang-16,

Thank you for using this module and tools for Alfresco.

1. Yes, I'm testing and work fine
2. If do you view the Scanning Action UI in Share?, then Alfviral is installed
3. In alfviral.properties in the subsystems
4. I recommending registry a enterprise suscription module for more assistance. Not is very spensive :)
5. The Alfviral not depending of the ASS, but I'm testing and work fine too

![image](https://user-images.githubusercontent.com/5998681/179397630-69d5513e-b5aa-4322-993f-73b7bf4693dd.png)

![image](https://user-images.githubusercontent.com/5998681/179397563-fa7fcec9-ce74-4cc7-870f-868d5a498927.png)

![image](https://user-images.githubusercontent.com/5998681/179398052-69c457a7-893a-46d0-aaf1-acdb15c7bbd8.png)
