### ISSUE TITLE
Maybe merge from fork https://github.com/xenit-eu/alfviral

### ISSUE THREAD

**Issue by shazada** [fegorama/alfviral#25]
It think it's good to merge some fixes from other forks, so this one keeps up to date.

**Comment by fegorama** [comment]
Hi Tahir!

Yes, good idea!

But, from forks or to forks?

Fernando González Ruano
Skype: fegorama

LinkedIn: https://www.linkedin.com/in/fegor/
GitHub: https://github.com/fegorama/
Blog: http://www.fegor.com/
