### ISSUE TITLE
Potential concurrency issues on scans

### ISSUE THREAD

**Issue by clegallic** [fegorama/alfviral#3]
Hi,
First of all, thanks for this great Alfresco extension.
We plan to deploy it soon on our Alfresco One 5.0 instance, but something in the design of the scan components looks strange to me, perhaps can you help me understand the way the module works ?

Scanning components ([InStreamScan](https://github.com/fegorama/alfviral/blob/f0f405090ec335bd5af3b84b174bc007f8b03cb5/alfviral/src/main/java/com/fegor/alfresco/security/antivirus/InStreamScan.java), CommandScan) are Spring based "singleton" beans, created in the [alfviral-context.xml](https://github.com/fegorama/alfviral/blob/e6dc06f03d4f874efd81df9361e61cac4995a571/alfviral/src/main/amp/config/alfresco/module/alfviral/context/alfviral-context.xml) context definition file.

As Spring beans are similar to singleton, there is only a single instance of each in the Spring application context.

Here is the potential identified risk : when scanning a file, the following code is used in [AntivirusService](https://github.com/fegorama/alfviral/blob/f0f405090ec335bd5af3b84b174bc007f8b03cb5/alfviral/src/main/java/com/fegor/alfresco/services/AntivirusService.java#L136)

```
inStreamScan.setData(contentReader.getContentString().getBytes());
res = inStreamScan.scan(nodeRef);
```

It works well when a single file is scanned, or if files are scanned sequentially.

But what happens if several files are scanned concurrently ?
As methods are not synchronized, there is a risk to switch to another file between inStreamScan.setData(...) call and  inStreamScan.scan(...) call.
And if a scan takes a long time to run, the nodeRef attribute of inStreamScan component may be updated during the scan to another nodeRef.

I may be wrong, as in fact I have not been able to setup a test platform to validate my assomptions.

Did I missed something is this a known limitation ?

Regards.

**Comment by fegorama** [comment]
Hi Charles,

Alfresco with Spring Framework uses ThreadLocal, which synchronises multiple calls to an object instance preventing a call to be run until the previous one has ended. Therefore, I think it is not necessary to deal with synchronization in this case, but I will verify the code to be on the safe side.

Thank you for your collaboration.

Regards, 

fegor

**Comment by clegallic** [comment]
Thanks for your answer.

I will also do some test to ensure that concurrency is not a problem.

In fact, I have been able to reproduce a similar problem with [CommandScan](https://github.com/fegorama/alfviral/blob/f0f405090ec335bd5af3b84b174bc007f8b03cb5/alfviral/src/main/java/com/fegor/alfresco/security/antivirus/CommandScan.java)

[Here](https://github.com/fegorama/alfviral/blob/f0f405090ec335bd5af3b84b174bc007f8b03cb5/alfviral/src/main/java/com/fegor/alfresco/security/antivirus/CommandScan.java#L79) the file to scan is appended to the command line for each new scan. But as previous filename is not removed from the "List\<String\> command" member, files to scan are added to previous ones instead of scanning only the current file.
For example, first call command will be "MYCOMMAND filepath1", and second one will be "MYCOMMAND filepath1 filepath2" instead of "MYCOMMAND filepath2".

Regards,

Charles

**Comment by fegorama** [comment]
Hi!

Yes, it is true, the list is not cleared after the script is called. I fix and soon launched a review.

Thank you for your contribution.

Regards,

Fegor

**Comment by fegorama** [comment]
Hi!

The problem with COMMAND is fixed in https://github.com/fegorama/alfviral/releases/tag/v1.3.4-SNAPSHOT

Regards, 

Fegor

**Comment by clegallic** [comment]
Hi,

Thanks, I will check and confirm you as soon as it will be possible.

Regards,

Charles
