### ISSUE TITLE
Using port other than 8080 produces errors

### ISSUE THREAD

**Issue by toby-cyberity** [fegorama/alfviral#4]
Hello,
I have installed alfviral on Alfresco Enterprise v5.0.2. The port Alfresco is using is alfresco.port=8084. After startup I try and access Alfresco through Share, but can't as it errors with:
INFO [webscripts.connector.RemoteClient] [http-apr-8084-exec-4] Exception calling (get) http://localhost:8080/alfresco/s/remoteadm/has/alfresco/site-data/component-types/webscript.xml?s=sitestore&alf_ticket=TICKET_3ewd9g7sd087sd0g7d076sa5tgsi
INFO [webscripts.connector.RemoteClient] [http-apr-8084-exec-4] Error status 503 Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused.

It works fine on port 8080. Can it be changed to work with ports other than 8080?

Many thanks.

**Comment by fegorama** [comment]
Hi!

That error is not from Alfviral.

Best regards,
Fegor
