### ISSUE TITLE
Encrypted datastore

### ISSUE THREAD

**Issue by toby-cyberity** [fegorama/alfviral#5]
Hi, we are trying to use Alfviral on an instance of Alfresco with an encrypted datastore. Is it possible to use either ICAP or Command scanning? If not, are there any plans to enable this.
Many thanks.

**Comment by fegorama** [comment]
When retrieving the content to be sent by ICAP it should be decrypted, anyway, let me check it.

**Comment by toby-cyberity** [comment]
Hi @fegorama, 

Have you managed to get any further with this issue?
We are wanting to use this functionality as soon as possible as it something we really like...

Thanks
Toby

**Comment by fegorama** [comment]
Hi @toby-cyberity 

The encryption in Alfresco (version 5 or later) is only for the enterprise version and with a special license, I do not have this license so I can not prove it. I am so sorry. :(

Best regards
Fegor
