### ISSUE TITLE
Aspects not applied after virus scan

### ISSUE THREAD

**Issue by petegallagher** [fegorama/alfviral#6]
Hi,

I'm testing this plugin against Alfresco 5.1.1 and I can see the log message for the Aspect being assigned e.g.:

```
14:53:03,706 INFO  [com.fegor.alfresco.security.antivirus.InStreamScan] [http-bio-8080-exec-5] com.fegor.alfresco.security.antivirus.InStreamScan: [Aspect SCANNED_FROM_CLAMAV assigned for 105bf47f-5686-4c8e-b760-6d5104ba1f40]
14:53:03,706 INFO  [com.fegor.alfresco.services.AntivirusService] [http-bio-8080-exec-5] com.fegor.alfresco.services.AntivirusService: [ALERT File: store://2017/2/15/14/53/8dfc44d3-b1ff-4f40-b388-e5b30dad7efd.bin is infected!]
```
However this does not appear to be reflected in the Alfresco UI e.g.:

<img width="747" alt="screen shot 2017-02-15 at 20 35 35" src="https://cloud.githubusercontent.com/assets/688331/22994413/c66a50de-f3be-11e6-9511-912a8ba110a8.png">

Is this expected? Or is there some other way of viewing Aspects assigned to the document?

**Comment by fegorama** [comment]
Hi!

Ok, in 5.0.x work fine but in 5.1.1/5.1.2 however, it is assigned but not shown in the share interface.

I look at it and fix it. Thank you for your contribution.

Regards,

Fegor
![aspects in one 5 1 2](https://cloud.githubusercontent.com/assets/5998681/23016164/e3c3709e-f435-11e6-9efc-40e212096182.png)
![aspects in one 5 1 2](https://cloud.githubusercontent.com/assets/5998681/23016169/e81a3150-f435-11e6-9ee1-1b21be4b78d5.png)

**Comment by fegorama** [comment]
Hi!, 

I have fixed it and it already works correctly in version 5.1.2. It will be available in the release of the new version 1.4.0.

Best regards,

Fegor


![fix aspects in one 5 1 2](https://cloud.githubusercontent.com/assets/5998681/23020201/343bcc46-f446-11e6-8eba-d1ef9631999e.png)

**Comment by petegallagher** [comment]
Amazing, thank you, look forward to the new release.

**Comment by petegallagher** [comment]
Just tested with 1.4.0 and the behaviour remains the same for me in 5.1.1.

**Comment by ayushiagrahari95** [comment]
Hi,

Have anyone tested it with command mode?
Because I am trying to scan the files for virus using command mode and it showing the exit code 127 which means that the command configured in alfresco-global.properties for clamav e.g alfviral.command.exe=/usr/bin/clamscan is not found although the command is running perfectly through terminal.

I am not able to figure out why this is so.
Any help would be greatly appreciatef

**Comment by fegorama** [comment]
Pleas, build a new issue for this problem (command mode).

Best regards.
