### ISSUE TITLE
Missing dependency for MVN build

### ISSUE THREAD

**Issue by petegallagher** [fegorama/alfviral#7]
When trying to build Alfviral locally there is a MVN dependency that cannot be resolved, excerpt below:

```xml
<dependency>
    <groupId>org.alfresco</groupId>
    <artifactId>alfresco-web-client</artifactId>
    <version>4.2.e</version>
    <classifier>classes</classifier>
    <scope>system</scope>
    <systemPath>D:/mvn_repo/org/alfresco/alfresco-web-client/4.2.e/alfresco-web-client-4.2.e.jar</systemPath>
</dependency>
```

Are there any details on where this file can be retrieved from to complete the build?

**Comment by fegorama** [comment]
Hi!

Yes, it is due to a bug in the maven libraries for the Alfresco SDK version 4.2, I have not yet changed to the new ones.

Solution:

Specify the local path to the 'alfresco-web-client-4.2.e.jar' library in the 'pom.xml' file for the dependency of the 'alfresco-web-client' artifact.

Best regards,

Fegor

**Comment by petegallagher** [comment]
Thanks Fegor, I had tried downloading https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-web-client/4.2.e/alfresco-web-client-4.2.e.jar and pointing it to that but got another error e.g.:

```
[ERROR] Failed to execute goal on project alfviral: Could not resolve dependencies for project com.fegor.alfresco:alfviral:amp:1.3.4-SNAPSHOT: Could not find artifact org.alfresco:alfresco-web-client:jar:classes:4.2.e at specified path /home/peterg/Downloads/alfresco-web-client-4.2.e.jar -> [Help 1]
```

Is there somewhere else to get this JAR from?

**Comment by fegorama** [comment]
But does not already have it in your maven repository, eg. {Maven_repository} /org/alfresco/alfresco-web-client/4.2.e?

If so, assuming {maven_repository} is mvn_repo:

```
		<dependency>
			<groupId>org.alfresco</groupId>
			<artifactId>alfresco-web-client</artifactId>
			<version>4.2.e</version>
			<classifier>classes</classifier>
			<scope>system</scope>
			<systemPath>/home/peterg/mvn_repo/org/alfresco/alfresco-web-client/4.2.e/alfresco-web-client-4.2.e.jar</systemPath>
		</dependency>
```

Is a local path. This library is for deprecated interface (/alfresco), in the future I remove.

**Comment by petegallagher** [comment]
I have it working now.

Thanks for your help!
