### ISSUE TITLE
Alfviral Doesn't work with CAS

### ISSUE THREAD

**Issue by mnesson** [fegorama/alfviral#8]
Hi,

We have an Alfresco 4.2.5.1 with CAS for SSO. A user login to CAS and he is redirected to his dashboard. But when we install Alfviral, redirection doesn't work. The user is redirected to the Alfresco authentication page.

Do you have solution? Any ideas?

Thanks!

**Comment by fegorama** [comment]
Hi!

I don't understant the relation with CAS but is possible. Please, can you send logs, configurations and all information possible. I'll install CAS and I test it.

Regards.

**Comment by fegorama** [comment]
I have not received any further information on this possible problem.
